### PR TITLE
Fix for app crashing occasionally on iOS

### PR DESCRIPTION
**Pull request by Martibis**
https://github.com/rurico/flutter_video_compress/issues/60#issue-499052434

### CODE REVIEW

**Comment by yy1300326388** [comment]
@Martibis @jonataslaw  This PR is effective and solved my crash.

**Comment by Martibis** [comment]
Thanks for merging @jonataslaw, any chance you could update it at pub dev too?

**Comment by jonataslaw** [comment]
I will update now

**Comment by jonataslaw** [comment]
@all-contributors please add @Martibis for maintenance

**Pull request merged**
