### PR TITLE
Update Kotlin dependencies

### PR DESCRIPTION
**Pull request by vbuberen**
This PR is one more update for Kotlin and Android dependencies to resolve build issues people have (like in #142).

I have updated everything to have latest stable versions as well as cleaned up a Gradle config for the `example` app to drop deprecated properties.
Also, updated changelogs to mention this update.

### CODE REVIEW

**Comment by vbuberen** [comment]
@jonataslaw Could I ask you to look at this PR and help to resolve issues, like #142 by releasing a new version of your library after merging this PR along with some other that you feel should be in the release?

**Comment by vbuberen** [comment]
@jonataslaw Pinging again as the problem is still there.

**Comment by Pascal-Orthopy** [comment]
@jonataslaw We have the same issue and would be happy to see this PR merged!

**Comment by JoDeveloper** [comment]
@jonataslaw would be very happy to see this PR merged!

**Comment by vbuberen** [comment]
@jonataslaw Since you were reviewing other PRs, would like to draw your attention to this one as well. I have just updated it to resolve conflicts, so it can be merged.

**Pull request closed without merging**
