### PR TITLE
Removed variable type of variables inside getMediaInfo and getFileThumbnail

### PR DESCRIPTION
**Pull request by trustmefelix**

### CODE REVIEW

**Comment by MaxSchilling** [comment]
@trustmefelix Could you add the exact same change to the getFileThumbnail() Method as well for your PR? Would be highly appreciated! Thanks heaps!

**Comment by trustmefelix** [comment]
> Edited - never mind - I went on and created a PR for the getFileThumbnail method in the same way you fixed the mediaInfo.

Thanks. I have just updated it on this PR.

**Comment by MaxSchilling** [comment]
I had to cancel the PR, still had the bug and error on the getFileThumbnail, didn't solve it like I thought in the first place.. any chance you have an idea? I'm out of ideas and built an own workaround with another thumbnail image package.. Would be way nicer to have it in one package again.

Many thanks!

**Comment by trustmefelix** [comment]
@MaxSchilling https://github.com/jonataslaw/VideoCompress/issues/105 should be fixed on this PR, may I know is there any other issue?

**Comment by getpu** [comment]
up up up fix !!!

**Comment by jonataslaw** [comment]
Wow, thanks for your contribution,
I will send to pub.dev asap
LGTM.

**Comment by curtinmartis** [comment]
@jonataslaw I've been running into this issue recently since I updated Flutter and enabled null safety. Looks like it never made it into a release. Any chance it can get pushed up to pub.dev sometime soon?

**Comment by zmhbh** [comment]
> @jonataslaw I've been running into this issue recently since I updated Flutter and enabled null safety. Looks like it never made it into a release. Any chance it can get pushed up to pub.dev sometime soon?

+1 same here.

**Comment by ccamba** [comment]
are you still waiting? Is this project alive?

**Comment by curtinmartis** [comment]
@ccamba There hasn't been a new release yet. I ended up just cloning the repo and referencing the project locally in `pubspec.yml` so I could use the fix in `master`. It works fine for me so far but I've only tested on a handful of Android devices.

**Pull request merged**
